run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - structcheck
    - unused
    - deadcode
    - gofmt
    - gosec
  disable:
    - maligned

issues:
  exclude-use-default: false
  max-same-issues: 3
  exclude:
    - "error return value not checked.*Close"
